// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_refresh_token.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getRefresh = `-- name: GetRefresh :one
SELECT 
    created_at,
    updated_at,
    user_id,
    expires_at,
    revoked_at
FROM
    refresh_tokens
WHERE
    token = $1
`

type GetRefreshRow struct {
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

func (q *Queries) GetRefresh(ctx context.Context, token string) (GetRefreshRow, error) {
	row := q.db.QueryRowContext(ctx, getRefresh, token)
	var i GetRefreshRow
	err := row.Scan(
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}
