// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_chirps_auth.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getChirpsAuth = `-- name: GetChirpsAuth :many
SELECT 
    id,
    created_at,
    updated_at,
    body,
    user_id
FROM
    chirps
WHERE
    user_id = $1
ORDER BY
    created_at ASC
`

func (q *Queries) GetChirpsAuth(ctx context.Context, userID uuid.UUID) ([]Chirp, error) {
	rows, err := q.db.QueryContext(ctx, getChirpsAuth, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chirp
	for rows.Next() {
		var i Chirp
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Body,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
