// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: update_users_password.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET updated_at = NOW(), hashed_password = $1, email = $2 WHERE id = $3
`

type UpdateUserPasswordParams struct {
	HashedPassword string
	Email          string
	ID             uuid.UUID
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.HashedPassword, arg.Email, arg.ID)
	return err
}
