// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: upgrade_to_red.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const upgeadeRed = `-- name: UpgeadeRed :exec
UPDATE users SET updated_at = NOW(), is_chirpy_red = true WHERE id = $1
`

func (q *Queries) UpgeadeRed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, upgeadeRed, id)
	return err
}
